version: '3'

services:
  app:
    build:
      context: .
    volumes:
      - ./app/:/app
    ports:
      - 3000:3000
  httpd:
    image: httpd:2.4-alpine
    volumes:
      - ./docker/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - 8080:80
    depends_on:
      - app
      